# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"
  config.vm.network "public_network"
  (1..3).each do |i|  
  config.vm.define "mesos-#{i}" do |mesos|
    config.vm.provider "virtualbox" do |mesos|
     mesos.memory = "1024"
     mesos.name = "mesos-#{i}"
     end
  end
  config.vm.provision "shell", inline: <<-SHELL
     yum -y update
   SHELL
  end
end
